PUBLIC_CORPUS = {
    "cs": [
    {"text": "data structures organize data efficiently", "source": "Wikipedia", "url": "https://wikipedia.org/data_structure"},
    {"text": "machine learning models learn patterns from data", "source": "GeeksForGeeks", "url": "https://geeksforgeeks.org/machine-learning"},
    {"text": "operating systems manage hardware resources", "source": "TutorialsPoint", "url": "https://tutorialspoint.com/os"},

    {"text": "algorithms provide logical steps to solve computational problems", "source": "MIT OpenCourseWare", "url": "https://ocw.mit.edu"},
    {"text": "arrays store elements in contiguous memory locations", "source": "Programiz", "url": "https://programiz.com"},
    {"text": "linked lists allow dynamic memory allocation in programs", "source": "GeeksForGeeks", "url": "https://geeksforgeeks.org"},
    {"text": "stacks follow last in first out order", "source": "W3Schools", "url": "https://w3schools.com"},
    {"text": "queues operate using first in first out principle", "source": "TutorialsPoint", "url": "https://tutorialspoint.com"},
    {"text": "binary trees organize hierarchical data structures", "source": "Wikipedia", "url": "https://wikipedia.org/binary_tree"},
    {"text": "hash tables enable fast key value lookups", "source": "Oracle Docs", "url": "https://docs.oracle.com"},
    {"text": "recursion solves problems by calling a function within itself", "source": "Khan Academy", "url": "https://khanacademy.org"},
    {"text": "dynamic programming optimizes problems by storing previous results", "source": "Stanford CS", "url": "https://cs.stanford.edu"},
    {"text": "time complexity measures algorithm efficiency", "source": "GeeksForGeeks", "url": "https://geeksforgeeks.org/time-complexity"},
    {"text": "big o notation describes growth rate of algorithms", "source": "Brilliant", "url": "https://brilliant.org"},
    {"text": "object oriented programming promotes code reusability", "source": "Oracle", "url": "https://oracle.com/java"},
    {"text": "encapsulation hides internal object details", "source": "Microsoft Learn", "url": "https://learn.microsoft.com"},
    {"text": "inheritance allows classes to derive properties from parent classes", "source": "Java Docs", "url": "https://docs.oracle.com/javase"},
    {"text": "polymorphism enables methods to behave differently based on input", "source": "GeeksForGeeks", "url": "https://geeksforgeeks.org/polymorphism"},
    {"text": "software testing ensures reliability of applications", "source": "ISTQB", "url": "https://istqb.org"},
    {"text": "unit testing validates individual components of code", "source": "JUnit", "url": "https://junit.org"},
    {"text": "agile methodology emphasizes iterative development cycles", "source": "Atlassian", "url": "https://atlassian.com/agile"},
    {"text": "version control systems track changes in source code", "source": "Git Docs", "url": "https://git-scm.com/docs"},
    {"text": "continuous integration automates build and testing workflows", "source": "GitHub Docs", "url": "https://docs.github.com"},
    {"text": "restful apis enable communication between client and server", "source": "MDN Web Docs", "url": "https://developer.mozilla.org"},
    {"text": "json format is commonly used for web data exchange", "source": "ECMA", "url": "https://json.org"},
    {"text": "databases maintain structured collections of data", "source": "PostgreSQL Docs", "url": "https://postgresql.org/docs"},
    {"text": "normalization reduces redundancy in relational databases", "source": "IBM", "url": "https://ibm.com"},
    {"text": "nosql databases handle unstructured data efficiently", "source": "MongoDB", "url": "https://mongodb.com"},
    {"text": "indexing improves query performance in databases", "source": "MySQL Docs", "url": "https://dev.mysql.com"},
    {"text": "computer networks use protocols to transfer data", "source": "Cisco", "url": "https://cisco.com"},
    {"text": "tcp ip model defines internet communication layers", "source": "Cloudflare", "url": "https://cloudflare.com/learning"},
    {"text": "encryption protects sensitive information from unauthorized access", "source": "NIST", "url": "https://nist.gov"},
    {"text": "firewalls monitor incoming and outgoing network traffic", "source": "Fortinet", "url": "https://fortinet.com"},
    {"text": "ethical hacking identifies vulnerabilities in systems", "source": "EC Council", "url": "https://eccouncil.org"},
    {"text": "cloud computing delivers on demand computing resources", "source": "AWS", "url": "https://aws.amazon.com"},
    {"text": "virtual machines emulate physical computer environments", "source": "VMware", "url": "https://vmware.com"},
    {"text": "containers package software with dependencies", "source": "Docker Docs", "url": "https://docs.docker.com"},
    {"text": "kubernetes automates deployment and scaling of containers", "source": "Kubernetes", "url": "https://kubernetes.io"},
    {"text": "artificial intelligence enables machines to perform cognitive tasks", "source": "IBM AI", "url": "https://ibm.com/ai"},
    {"text": "natural language processing helps computers understand text", "source": "HuggingFace", "url": "https://huggingface.co"},
    {"text": "computer vision analyzes visual data using neural networks", "source": "OpenCV", "url": "https://opencv.org"},
    {"text": "deep learning models require large datasets for training", "source": "DeepLearning.ai", "url": "https://deeplearning.ai"},
    {"text": "feature engineering improves machine learning performance", "source": "Scikit Learn", "url": "https://scikit-learn.org"},
    {"text": "model evaluation uses metrics like accuracy precision and recall", "source": "Google ML Crash Course", "url": "https://developers.google.com/machine-learning"},
    {"text": "data preprocessing includes cleaning normalization and transformation", "source": "Kaggle Learn", "url": "https://kaggle.com/learn"},
    {"text": "distributed systems ensure scalability across multiple machines", "source": "Google Cloud", "url": "https://cloud.google.com"},
    {"text": "parallel computing executes tasks simultaneously to improve performance", "source": "NVIDIA", "url": "https://developer.nvidia.com"},
    {"text": "edge computing processes data closer to the source device", "source": "Intel", "url": "https://intel.com/edge-computing"},
],
"science": [
    {"text": "photosynthesis converts light energy into chemical energy", "source": "Britannica", "url": "https://britannica.com/photosynthesis"},
    {"text": "newton laws describe motion and force", "source": "NASA", "url": "https://nasa.gov/newton-laws"},
    {"text": "cells are the basic unit of life", "source": "Wikipedia", "url": "https://wikipedia.org/cell"},

    {"text": "atoms consist of protons neutrons and electrons", "source": "ChemLibreTexts", "url": "https://chem.libretexts.org"},
    {"text": "the periodic table organizes elements based on atomic number", "source": "Royal Society of Chemistry", "url": "https://rsc.org"},
    {"text": "chemical reactions involve breaking and forming of bonds", "source": "Khan Academy", "url": "https://khanacademy.org"},
    {"text": "acids and bases are measured using the ph scale", "source": "LibreTexts", "url": "https://chem.libretexts.org"},
    {"text": "thermodynamics studies energy transfer and heat systems", "source": "MIT Physics", "url": "https://physics.mit.edu"},
    {"text": "the law of conservation of energy states energy cannot be created or destroyed", "source": "Physics Classroom", "url": "https://physicsclassroom.com"},
    {"text": "kinetic energy depends on mass and velocity of objects", "source": "NASA", "url": "https://nasa.gov"},
    {"text": "gravity governs the motion of planets and celestial bodies", "source": "ESA", "url": "https://esa.int"},
    {"text": "the electromagnetic spectrum includes visible light and radio waves", "source": "NOAA", "url": "https://noaa.gov"},
    {"text": "waves transfer energy without transporting matter", "source": "OpenStax", "url": "https://openstax.org"},
    {"text": "electric current is the flow of charged particles", "source": "All About Circuits", "url": "https://allaboutcircuits.com"},
    {"text": "magnetic fields are produced by moving electric charges", "source": "HyperPhysics", "url": "http://hyperphysics.phy-astr.gsu.edu"},
    {"text": "ecosystems include interactions between living organisms and environment", "source": "WWF", "url": "https://wwf.org"},
    {"text": "biodiversity refers to the variety of life forms on earth", "source": "UNEP", "url": "https://unep.org"},
    {"text": "food chains describe energy flow between organisms", "source": "National Geographic", "url": "https://nationalgeographic.com"},
    {"text": "genetics studies inheritance through dna sequences", "source": "Genome.gov", "url": "https://genome.gov"},
    {"text": "mutations are changes in genetic material that may affect traits", "source": "NIH", "url": "https://nih.gov"},
    {"text": "evolution explains species adaptation through natural selection", "source": "Darwin Online", "url": "https://darwin-online.org.uk"},
    {"text": "the human circulatory system transports oxygen and nutrients", "source": "MedlinePlus", "url": "https://medlineplus.gov"},
    {"text": "respiration releases energy from glucose in living cells", "source": "BBC Bitesize", "url": "https://bbc.co.uk/bitesize"},
    {"text": "enzymes act as biological catalysts speeding up reactions", "source": "Biology LibreTexts", "url": "https://bio.libretexts.org"},
    {"text": "homeostasis maintains stable internal body conditions", "source": "Khan Academy", "url": "https://khanacademy.org"},
    {"text": "the nervous system transmits electrical signals across neurons", "source": "NIH", "url": "https://nih.gov"},
    {"text": "plate tectonics explains movement of earth crust layers", "source": "USGS", "url": "https://usgs.gov"},
    {"text": "volcanoes form when magma rises through earth surface", "source": "Smithsonian", "url": "https://smithsonianmag.com"},
    {"text": "earth atmosphere contains nitrogen oxygen and trace gases", "source": "NASA Earth Science", "url": "https://earthdata.nasa.gov"},
    {"text": "climate change refers to long term shifts in global temperature", "source": "IPCC", "url": "https://ipcc.ch"},
    {"text": "greenhouse gases trap heat within the atmosphere", "source": "EPA", "url": "https://epa.gov"},
    {"text": "renewable energy sources include solar wind and hydro power", "source": "IEA", "url": "https://iea.org"},
    {"text": "astronomy studies stars galaxies and cosmic phenomena", "source": "HubbleSite", "url": "https://hubblesite.org"},
    {"text": "black holes possess gravitational fields so strong that light cannot escape", "source": "NASA", "url": "https://nasa.gov/black-holes"},
    {"text": "the solar system consists of planets orbiting the sun", "source": "ESA", "url": "https://esa.int"},
    {"text": "scientific method involves observation hypothesis experimentation and conclusion", "source": "Science Buddies", "url": "https://sciencebuddies.org"},
    {"text": "peer review ensures reliability of scientific research", "source": "Nature", "url": "https://nature.com"},
    {"text": "nanotechnology manipulates materials at atomic scale", "source": "Nano.gov", "url": "https://nano.gov"},
    {"text": "biotechnology uses living organisms to develop products", "source": "WHO", "url": "https://who.int"},
    {"text": "vaccines stimulate immune response against diseases", "source": "CDC", "url": "https://cdc.gov"},
    {"text": "microorganisms include bacteria viruses and fungi", "source": "Microbiology Society", "url": "https://microbiologysociety.org"},
],
"commerce": [
    {"text": "demand and supply determine market prices", "source": "Investopedia", "url": "https://investopedia.com/demand-supply"},
    {"text": "accounting records financial transactions", "source": "AccountingCoach", "url": "https://accountingcoach.com"},
    {"text": "marketing focuses on customer value", "source": "HubSpot", "url": "https://hubspot.com/marketing"},

    {"text": "financial accounting prepares balance sheets and income statements", "source": "IFRS", "url": "https://ifrs.org"},
    {"text": "managerial accounting helps internal decision making", "source": "Corporate Finance Institute", "url": "https://corporatefinanceinstitute.com"},
    {"text": "cost accounting analyzes production and operational expenses", "source": "AccountingTools", "url": "https://accountingtools.com"},
    {"text": "assets liabilities and equity form the accounting equation", "source": "Investopedia", "url": "https://investopedia.com/accounting-equation"},
    {"text": "depreciation allocates asset cost over useful life", "source": "IRS", "url": "https://irs.gov"},
    {"text": "cash flow statements track movement of funds in business operations", "source": "Harvard Business School", "url": "https://online.hbs.edu"},
    {"text": "budgeting helps organizations control financial performance", "source": "CFI", "url": "https://corporatefinanceinstitute.com"},

    {"text": "microeconomics studies behavior of individuals and firms", "source": "Khan Academy", "url": "https://khanacademy.org"},
    {"text": "macroeconomics analyzes national income inflation and unemployment", "source": "IMF", "url": "https://imf.org"},
    {"text": "elasticity measures responsiveness of demand to price changes", "source": "Investopedia", "url": "https://investopedia.com/elasticity"},
    {"text": "monopoly markets involve single dominant sellers", "source": "EconomicsHelp", "url": "https://economicshelp.org"},
    {"text": "perfect competition occurs when many buyers and sellers exist", "source": "OpenStax", "url": "https://openstax.org"},
    {"text": "gross domestic product measures economic output", "source": "World Bank", "url": "https://worldbank.org"},
    {"text": "inflation represents rising price levels over time", "source": "Federal Reserve", "url": "https://federalreserve.gov"},

    {"text": "branding builds recognition and emotional connection with consumers", "source": "Interbrand", "url": "https://interbrand.com"},
    {"text": "market segmentation divides customers into specific groups", "source": "Kotler Marketing", "url": "https://kotlermarketing.com"},
    {"text": "digital marketing uses search engines and social media platforms", "source": "Google Digital Garage", "url": "https://learndigital.withgoogle.com"},
    {"text": "consumer behavior studies decision making processes of buyers", "source": "Springer", "url": "https://springer.com"},
    {"text": "product life cycle includes introduction growth maturity and decline", "source": "MindTools", "url": "https://mindtools.com"},
    {"text": "pricing strategies influence perceived value of products", "source": "Forbes", "url": "https://forbes.com"},
    {"text": "advertising promotes products through persuasive communication", "source": "American Marketing Association", "url": "https://ama.org"},

    {"text": "human resource management handles recruitment training and performance evaluation", "source": "SHRM", "url": "https://shrm.org"},
    {"text": "leadership styles impact organizational culture", "source": "Harvard Business Review", "url": "https://hbr.org"},
    {"text": "organizational behavior studies workplace dynamics", "source": "McGraw Hill", "url": "https://mheducation.com"},
    {"text": "business ethics encourage responsible corporate practices", "source": "Ethics.org", "url": "https://ethics.org"},
    {"text": "strategic management involves long term planning and analysis", "source": "Porter Institute", "url": "https://porterinstitute.com"},

    {"text": "e commerce enables online buying and selling of goods", "source": "Shopify", "url": "https://shopify.com"},
    {"text": "supply chain management coordinates production and distribution processes", "source": "APICS", "url": "https://apics.org"},
    {"text": "logistics ensures efficient movement of products", "source": "DHL", "url": "https://dhl.com"},
    {"text": "entrepreneurship involves innovation risk taking and business creation", "source": "Entrepreneur", "url": "https://entrepreneur.com"},
    {"text": "venture capital funds startups with high growth potential", "source": "Crunchbase", "url": "https://crunchbase.com"},
    {"text": "stock markets allow investors to trade company shares", "source": "NASDAQ", "url": "https://nasdaq.com"},
    {"text": "diversification reduces investment risk in portfolios", "source": "Morningstar", "url": "https://morningstar.com"},
    {"text": "international trade connects global markets and economies", "source": "World Trade Organization", "url": "https://wto.org"},
    {"text": "foreign exchange markets determine currency values", "source": "Investopedia", "url": "https://investopedia.com/forex"},
],
    "general": [
    {"text": "education improves quality of life", "source": "UNESCO", "url": "https://unesco.org"},
    {"text": "technology impacts modern society", "source": "WorldEconomicForum", "url": "https://weforum.org"},
    {"text": "research solves real world problems", "source": "Nature Journal", "url": "https://nature.com"},

    {"text": "communication skills are essential for personal and professional growth", "source": "LinkedIn Learning", "url": "https://linkedin.com/learning"},
    {"text": "critical thinking helps evaluate information logically", "source": "Edutopia", "url": "https://edutopia.org"},
    {"text": "time management improves productivity and reduces stress", "source": "Coursera", "url": "https://coursera.org"},
    {"text": "leadership involves guiding teams toward shared goals", "source": "MindTools", "url": "https://mindtools.com"},
    {"text": "collaboration encourages innovation through diverse perspectives", "source": "Atlassian", "url": "https://atlassian.com"},
    {"text": "problem solving skills help individuals overcome complex challenges", "source": "Cambridge", "url": "https://cambridge.org"},
    {"text": "digital literacy is important in modern education systems", "source": "OECD", "url": "https://oecd.org"},
    {"text": "adaptability allows individuals to succeed in changing environments", "source": "Forbes", "url": "https://forbes.com"},
    {"text": "creativity drives innovation across industries", "source": "FastCompany", "url": "https://fastcompany.com"},
    {"text": "emotional intelligence improves interpersonal relationships", "source": "Psychology Today", "url": "https://psychologytoday.com"},
    {"text": "lifelong learning supports continuous personal development", "source": "World Bank", "url": "https://worldbank.org"},
    {"text": "healthy lifestyle includes balanced diet and regular exercise", "source": "WHO", "url": "https://who.int"},
    {"text": "mental health awareness promotes emotional well being", "source": "NIMH", "url": "https://nimh.nih.gov"},
    {"text": "sustainability focuses on balancing environment economy and society", "source": "UNDP", "url": "https://undp.org"},
    {"text": "globalization connects cultures economies and technologies worldwide", "source": "IMF", "url": "https://imf.org"},
    {"text": "media literacy helps people analyze information from digital platforms", "source": "Common Sense Media", "url": "https://commonsensemedia.org"},
    {"text": "ethics guide responsible decision making in society", "source": "Stanford Encyclopedia", "url": "https://plato.stanford.edu"},
    {"text": "innovation drives economic and technological advancement", "source": "McKinsey", "url": "https://mckinsey.com"},
    {"text": "volunteering strengthens community engagement and social responsibility", "source": "UN Volunteers", "url": "https://unv.org"},
    {"text": "public speaking improves confidence and persuasion skills", "source": "Toastmasters", "url": "https://toastmasters.org"},
    {"text": "goal setting helps individuals track progress and achievements", "source": "Harvard Business Review", "url": "https://hbr.org"},
    {"text": "teamwork improves efficiency in collaborative environments", "source": "Indeed Career Guide", "url": "https://indeed.com"},
    {"text": "digital transformation reshapes modern workplaces", "source": "Gartner", "url": "https://gartner.com"},
    {"text": "information overload requires strong filtering and prioritization skills", "source": "MIT Sloan", "url": "https://mitsloan.mit.edu"},
    {"text": "ethical use of technology ensures privacy and data protection", "source": "Electronic Frontier Foundation", "url": "https://eff.org"},
    {"text": "cultural diversity promotes understanding and creativity", "source": "UNESCO", "url": "https://unesco.org/diversity"},
    {"text": "financial literacy helps individuals manage money effectively", "source": "FDIC", "url": "https://fdic.gov"},
    {"text": "remote work relies on communication tools and self discipline", "source": "Buffer", "url": "https://buffer.com"},
    {"text": "social responsibility encourages sustainable development goals", "source": "UN SDGs", "url": "https://sdgs.un.org"},
],
}